language: python
python:
  - "2.7"
install:
  - pip install -q -r requirements.pip --use-mirrors
  - pip install coveralls nose-cov
script: nosetests --with-coverage --cover-package pyxform --cov-config .coveragerc
after_success: coveralls
notifications:
  irc: "irc.freenode.org#moditest"
