sudo: false
language: python
python:
  - "2.7"
install:
  - pip install -q -r requirements.pip --use-mirrors
  - pip install coveralls nose-cov
cache: pip
script: nosetests -c .noserc --with-coverage --cover-package pyxform --cov-config .coveragerc
after_success: coveralls
