sudo: false
language: python
python:
  - "2.7"
install:
  - pip install -r requirements.pip
  - pip install coveralls nose-cov 'coverage<4'
cache: pip
script: nosetests -c .noserc --with-coverage --cover-package pyxform --cov-config .coveragerc
after_success: coveralls
